<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Documentosvehiculos extends \Entity\Documentosvehiculos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'id', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathlicencia', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathtarjetapropiedad', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathtarjetaoperacion', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathsoat', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathtecnomecanica', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'cedulaconductor', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'createdAt', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'idvehiculo', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'idestado');
        }

        return array('__isInitialized__', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'id', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathlicencia', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathtarjetapropiedad', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathtarjetaoperacion', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathsoat', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'pathtecnomecanica', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'cedulaconductor', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'createdAt', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'idvehiculo', '' . "\0" . 'Entity\\Documentosvehiculos' . "\0" . 'idestado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Documentosvehiculos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathlicencia($pathlicencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathlicencia', array($pathlicencia));

        return parent::setPathlicencia($pathlicencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathlicencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathlicencia', array());

        return parent::getPathlicencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathtarjetapropiedad($pathtarjetapropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathtarjetapropiedad', array($pathtarjetapropiedad));

        return parent::setPathtarjetapropiedad($pathtarjetapropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathtarjetapropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathtarjetapropiedad', array());

        return parent::getPathtarjetapropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathtarjetaoperacion($pathtarjetaoperacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathtarjetaoperacion', array($pathtarjetaoperacion));

        return parent::setPathtarjetaoperacion($pathtarjetaoperacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathtarjetaoperacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathtarjetaoperacion', array());

        return parent::getPathtarjetaoperacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathsoat($pathsoat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathsoat', array($pathsoat));

        return parent::setPathsoat($pathsoat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathsoat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathsoat', array());

        return parent::getPathsoat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathtecnomecanica($pathtecnomecanica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathtecnomecanica', array($pathtecnomecanica));

        return parent::setPathtecnomecanica($pathtecnomecanica);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathtecnomecanica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathtecnomecanica', array());

        return parent::getPathtecnomecanica();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedulaconductor($cedulaconductor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedulaconductor', array($cedulaconductor));

        return parent::setCedulaconductor($cedulaconductor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedulaconductor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedulaconductor', array());

        return parent::getCedulaconductor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdvehiculo(\Entity\Vehiculos $idvehiculo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdvehiculo', array($idvehiculo));

        return parent::setIdvehiculo($idvehiculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdvehiculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdvehiculo', array());

        return parent::getIdvehiculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado(\Entity\Estados $idestado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', array($idestado));

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', array());

        return parent::getIdestado();
    }

}
