<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Registros extends \Entity\Registros implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entity\\Registros' . "\0" . 'id', '' . "\0" . 'Entity\\Registros' . "\0" . 'nombres', '' . "\0" . 'Entity\\Registros' . "\0" . 'apellidos', '' . "\0" . 'Entity\\Registros' . "\0" . 'identificacion', '' . "\0" . 'Entity\\Registros' . "\0" . 'nacimiento', '' . "\0" . 'Entity\\Registros' . "\0" . 'direccion', '' . "\0" . 'Entity\\Registros' . "\0" . 'telefono', '' . "\0" . 'Entity\\Registros' . "\0" . 'pathimage', '' . "\0" . 'Entity\\Registros' . "\0" . 'createdAt', '' . "\0" . 'Entity\\Registros' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\Registros' . "\0" . 'billetera', '' . "\0" . 'Entity\\Registros' . "\0" . 'idpais', '' . "\0" . 'Entity\\Registros' . "\0" . 'idtipoidentificacion', '' . "\0" . 'Entity\\Registros' . "\0" . 'idlugarexpedicion', '' . "\0" . 'Entity\\Registros' . "\0" . 'idciudad', '' . "\0" . 'Entity\\Registros' . "\0" . 'idestadoregistro', '' . "\0" . 'Entity\\Registros' . "\0" . 'idrol', '' . "\0" . 'Entity\\Registros' . "\0" . 'idusuario');
        }

        return array('__isInitialized__', '' . "\0" . 'Entity\\Registros' . "\0" . 'id', '' . "\0" . 'Entity\\Registros' . "\0" . 'nombres', '' . "\0" . 'Entity\\Registros' . "\0" . 'apellidos', '' . "\0" . 'Entity\\Registros' . "\0" . 'identificacion', '' . "\0" . 'Entity\\Registros' . "\0" . 'nacimiento', '' . "\0" . 'Entity\\Registros' . "\0" . 'direccion', '' . "\0" . 'Entity\\Registros' . "\0" . 'telefono', '' . "\0" . 'Entity\\Registros' . "\0" . 'pathimage', '' . "\0" . 'Entity\\Registros' . "\0" . 'createdAt', '' . "\0" . 'Entity\\Registros' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\Registros' . "\0" . 'billetera', '' . "\0" . 'Entity\\Registros' . "\0" . 'idpais', '' . "\0" . 'Entity\\Registros' . "\0" . 'idtipoidentificacion', '' . "\0" . 'Entity\\Registros' . "\0" . 'idlugarexpedicion', '' . "\0" . 'Entity\\Registros' . "\0" . 'idciudad', '' . "\0" . 'Entity\\Registros' . "\0" . 'idestadoregistro', '' . "\0" . 'Entity\\Registros' . "\0" . 'idrol', '' . "\0" . 'Entity\\Registros' . "\0" . 'idusuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Registros $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombres($nombres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombres', array($nombres));

        return parent::setNombres($nombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombres', array());

        return parent::getNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentificacion($identificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentificacion', array($identificacion));

        return parent::setIdentificacion($identificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentificacion', array());

        return parent::getIdentificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacimiento($nacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacimiento', array($nacimiento));

        return parent::setNacimiento($nacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacimiento', array());

        return parent::getNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathimage($pathimage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathimage', array($pathimage));

        return parent::setPathimage($pathimage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathimage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathimage', array());

        return parent::getPathimage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBilletera($billetera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBilletera', array($billetera));

        return parent::setBilletera($billetera);
    }

    /**
     * {@inheritDoc}
     */
    public function getBilletera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBilletera', array());

        return parent::getBilletera();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpais(\Entity\Paises $idpais = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpais', array($idpais));

        return parent::setIdpais($idpais);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpais', array());

        return parent::getIdpais();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipoidentificacion(\Entity\Tipoidentificacion $idtipoidentificacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipoidentificacion', array($idtipoidentificacion));

        return parent::setIdtipoidentificacion($idtipoidentificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipoidentificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipoidentificacion', array());

        return parent::getIdtipoidentificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdlugarexpedicion(\Entity\Ciudades $idlugarexpedicion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdlugarexpedicion', array($idlugarexpedicion));

        return parent::setIdlugarexpedicion($idlugarexpedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdlugarexpedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlugarexpedicion', array());

        return parent::getIdlugarexpedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdciudad(\Entity\Ciudades $idciudad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdciudad', array($idciudad));

        return parent::setIdciudad($idciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdciudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdciudad', array());

        return parent::getIdciudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestadoregistro(\Entity\Estados $idestadoregistro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestadoregistro', array($idestadoregistro));

        return parent::setIdestadoregistro($idestadoregistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestadoregistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestadoregistro', array());

        return parent::getIdestadoregistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrol(\Entity\Roles $idrol = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrol', array($idrol));

        return parent::setIdrol($idrol);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrol', array());

        return parent::getIdrol();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\Entity\Usuarios $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', array($idusuario));

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', array());

        return parent::getIdusuario();
    }

}
