<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Precioreserva extends \Entity\Precioreserva implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'id', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'embajale', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'distancia', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'seguro', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'porcentaje', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'total', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idreserva', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idtamano', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idsubcategoria', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idayudantes');
        }

        return array('__isInitialized__', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'id', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'embajale', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'distancia', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'seguro', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'porcentaje', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'total', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idreserva', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idtamano', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idsubcategoria', '' . "\0" . 'Entity\\Precioreserva' . "\0" . 'idayudantes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Precioreserva $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmbajale($embajale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmbajale', array($embajale));

        return parent::setEmbajale($embajale);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmbajale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmbajale', array());

        return parent::getEmbajale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistancia($distancia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistancia', array($distancia));

        return parent::setDistancia($distancia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistancia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistancia', array());

        return parent::getDistancia();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeguro($seguro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeguro', array($seguro));

        return parent::setSeguro($seguro);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeguro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeguro', array());

        return parent::getSeguro();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentaje($porcentaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentaje', array($porcentaje));

        return parent::setPorcentaje($porcentaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentaje', array());

        return parent::getPorcentaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdreserva(\Entity\Reservas $idreserva = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdreserva', array($idreserva));

        return parent::setIdreserva($idreserva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdreserva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdreserva', array());

        return parent::getIdreserva();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtamano(\Entity\Tamanocasa $idtamano = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtamano', array($idtamano));

        return parent::setIdtamano($idtamano);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtamano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtamano', array());

        return parent::getIdtamano();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsubcategoria(\Entity\Subcategoria $idsubcategoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsubcategoria', array($idsubcategoria));

        return parent::setIdsubcategoria($idsubcategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsubcategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsubcategoria', array());

        return parent::getIdsubcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdayudantes(\Entity\Ayudantes $idayudantes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdayudantes', array($idayudantes));

        return parent::setIdayudantes($idayudantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdayudantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdayudantes', array());

        return parent::getIdayudantes();
    }

}
