<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehiculos extends \Entity\Vehiculos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'id', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'placa', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'modelo', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'marcar', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'color', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'tarjetapropiedad', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'capacidad', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerochasis', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerotarjetaoperacion', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'expidetarjetaoperacion', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'vencimientotarjetaoperacion', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerotecnomecanica', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'expidetecnomecanica', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'vencimientotecnomecanica', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerosoat', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'expidesoat', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'vencimientosoat', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'idestado');
        }

        return array('__isInitialized__', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'id', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'placa', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'modelo', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'marcar', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'color', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'tarjetapropiedad', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'capacidad', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerochasis', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerotarjetaoperacion', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'expidetarjetaoperacion', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'vencimientotarjetaoperacion', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerotecnomecanica', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'expidetecnomecanica', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'vencimientotecnomecanica', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'numerosoat', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'expidesoat', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'vencimientosoat', '' . "\0" . 'Entity\\Vehiculos' . "\0" . 'idestado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehiculos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaca($placa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaca', array($placa));

        return parent::setPlaca($placa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaca', array());

        return parent::getPlaca();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelo($modelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelo', array($modelo));

        return parent::setModelo($modelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', array());

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarcar($marcar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarcar', array($marcar));

        return parent::setMarcar($marcar);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarcar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarcar', array());

        return parent::getMarcar();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', array($color));

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', array());

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarjetapropiedad($tarjetapropiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarjetapropiedad', array($tarjetapropiedad));

        return parent::setTarjetapropiedad($tarjetapropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarjetapropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarjetapropiedad', array());

        return parent::getTarjetapropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacidad($capacidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacidad', array($capacidad));

        return parent::setCapacidad($capacidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidad', array());

        return parent::getCapacidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumerochasis($numerochasis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumerochasis', array($numerochasis));

        return parent::setNumerochasis($numerochasis);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumerochasis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumerochasis', array());

        return parent::getNumerochasis();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumerotarjetaoperacion($numerotarjetaoperacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumerotarjetaoperacion', array($numerotarjetaoperacion));

        return parent::setNumerotarjetaoperacion($numerotarjetaoperacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumerotarjetaoperacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumerotarjetaoperacion', array());

        return parent::getNumerotarjetaoperacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpidetarjetaoperacion($expidetarjetaoperacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpidetarjetaoperacion', array($expidetarjetaoperacion));

        return parent::setExpidetarjetaoperacion($expidetarjetaoperacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpidetarjetaoperacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpidetarjetaoperacion', array());

        return parent::getExpidetarjetaoperacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVencimientotarjetaoperacion($vencimientotarjetaoperacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVencimientotarjetaoperacion', array($vencimientotarjetaoperacion));

        return parent::setVencimientotarjetaoperacion($vencimientotarjetaoperacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getVencimientotarjetaoperacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVencimientotarjetaoperacion', array());

        return parent::getVencimientotarjetaoperacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumerotecnomecanica($numerotecnomecanica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumerotecnomecanica', array($numerotecnomecanica));

        return parent::setNumerotecnomecanica($numerotecnomecanica);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumerotecnomecanica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumerotecnomecanica', array());

        return parent::getNumerotecnomecanica();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpidetecnomecanica($expidetecnomecanica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpidetecnomecanica', array($expidetecnomecanica));

        return parent::setExpidetecnomecanica($expidetecnomecanica);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpidetecnomecanica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpidetecnomecanica', array());

        return parent::getExpidetecnomecanica();
    }

    /**
     * {@inheritDoc}
     */
    public function setVencimientotecnomecanica($vencimientotecnomecanica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVencimientotecnomecanica', array($vencimientotecnomecanica));

        return parent::setVencimientotecnomecanica($vencimientotecnomecanica);
    }

    /**
     * {@inheritDoc}
     */
    public function getVencimientotecnomecanica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVencimientotecnomecanica', array());

        return parent::getVencimientotecnomecanica();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumerosoat($numerosoat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumerosoat', array($numerosoat));

        return parent::setNumerosoat($numerosoat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumerosoat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumerosoat', array());

        return parent::getNumerosoat();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpidesoat($expidesoat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpidesoat', array($expidesoat));

        return parent::setExpidesoat($expidesoat);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpidesoat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpidesoat', array());

        return parent::getExpidesoat();
    }

    /**
     * {@inheritDoc}
     */
    public function setVencimientosoat($vencimientosoat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVencimientosoat', array($vencimientosoat));

        return parent::setVencimientosoat($vencimientosoat);
    }

    /**
     * {@inheritDoc}
     */
    public function getVencimientosoat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVencimientosoat', array());

        return parent::getVencimientosoat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado(\Entity\Estados $idestado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', array($idestado));

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', array());

        return parent::getIdestado();
    }

}
