<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Historialpagos extends \Entity\Historialpagos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'id', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'fecharecarga', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'valorrecarga', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'numtransaccion', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'idregistro', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'idmediopago', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'idestado');
        }

        return array('__isInitialized__', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'id', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'fecharecarga', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'valorrecarga', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'numtransaccion', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'idregistro', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'idmediopago', '' . "\0" . 'Entity\\Historialpagos' . "\0" . 'idestado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Historialpagos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharecarga($fecharecarga)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharecarga', array($fecharecarga));

        return parent::setFecharecarga($fecharecarga);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharecarga()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharecarga', array());

        return parent::getFecharecarga();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorrecarga($valorrecarga)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorrecarga', array($valorrecarga));

        return parent::setValorrecarga($valorrecarga);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorrecarga()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorrecarga', array());

        return parent::getValorrecarga();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumtransaccion($numtransaccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumtransaccion', array($numtransaccion));

        return parent::setNumtransaccion($numtransaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumtransaccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumtransaccion', array());

        return parent::getNumtransaccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdregistro(\Entity\Registros $idregistro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdregistro', array($idregistro));

        return parent::setIdregistro($idregistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdregistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdregistro', array());

        return parent::getIdregistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmediopago(\Entity\Mediopago $idmediopago = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmediopago', array($idmediopago));

        return parent::setIdmediopago($idmediopago);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmediopago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmediopago', array());

        return parent::getIdmediopago();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado(\Entity\Estados $idestado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', array($idestado));

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', array());

        return parent::getIdestado();
    }

}
