<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservas extends \Entity\Reservas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entity\\Reservas' . "\0" . 'id', '' . "\0" . 'Entity\\Reservas' . "\0" . 'descripcion', '' . "\0" . 'Entity\\Reservas' . "\0" . 'aksalida', '' . "\0" . 'Entity\\Reservas' . "\0" . 'dirsalida', '' . "\0" . 'Entity\\Reservas' . "\0" . 'akllegada', '' . "\0" . 'Entity\\Reservas' . "\0" . 'dirllegada', '' . "\0" . 'Entity\\Reservas' . "\0" . 'idconductor', '' . "\0" . 'Entity\\Reservas' . "\0" . 'idestado', '' . "\0" . 'Entity\\Reservas' . "\0" . 'idusuario');
        }

        return array('__isInitialized__', '' . "\0" . 'Entity\\Reservas' . "\0" . 'id', '' . "\0" . 'Entity\\Reservas' . "\0" . 'descripcion', '' . "\0" . 'Entity\\Reservas' . "\0" . 'aksalida', '' . "\0" . 'Entity\\Reservas' . "\0" . 'dirsalida', '' . "\0" . 'Entity\\Reservas' . "\0" . 'akllegada', '' . "\0" . 'Entity\\Reservas' . "\0" . 'dirllegada', '' . "\0" . 'Entity\\Reservas' . "\0" . 'idconductor', '' . "\0" . 'Entity\\Reservas' . "\0" . 'idestado', '' . "\0" . 'Entity\\Reservas' . "\0" . 'idusuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reservas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAksalida($aksalida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAksalida', array($aksalida));

        return parent::setAksalida($aksalida);
    }

    /**
     * {@inheritDoc}
     */
    public function getAksalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAksalida', array());

        return parent::getAksalida();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirsalida($dirsalida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirsalida', array($dirsalida));

        return parent::setDirsalida($dirsalida);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirsalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirsalida', array());

        return parent::getDirsalida();
    }

    /**
     * {@inheritDoc}
     */
    public function setAkllegada($akllegada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAkllegada', array($akllegada));

        return parent::setAkllegada($akllegada);
    }

    /**
     * {@inheritDoc}
     */
    public function getAkllegada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAkllegada', array());

        return parent::getAkllegada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirllegada($dirllegada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirllegada', array($dirllegada));

        return parent::setDirllegada($dirllegada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirllegada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirllegada', array());

        return parent::getDirllegada();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdconductor(\Entity\Conductores $idconductor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdconductor', array($idconductor));

        return parent::setIdconductor($idconductor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdconductor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdconductor', array());

        return parent::getIdconductor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado(\Entity\Estados $idestado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', array($idestado));

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', array());

        return parent::getIdestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\Entity\Usuarios $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', array($idusuario));

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', array());

        return parent::getIdusuario();
    }

}
